Update projects page
veganhacktivists/veganhacktivists pull request #159
Opened 2022-10-13 14:13 UTC by malinatran

2022-10-13 15:15 UTC, davidvanbeveren submitted a review, later dismissed

2022-10-14 11:49 UTC, davidvanbeveren submitted a review, later dismissed

2022-10-14 11:57 UTC, Headscracher requested changes

2022-10-14 11:57 UTC, Headscracher commented on src/pages/projects/index.tsx
> +        ones, whether they're in-house or in support of other organizations.
```suggestion
        ones, whether they&apos;re in-house or in support of other organizations.
```

2022-10-14 12:38 UTC, davidvanbeveren commented on src/pages/projects/index.tsx
> +        ones, whether they're in-house or in support of other organizations.
@Headscracher Same for this one? ’

2022-10-14 12:40 UTC, malinatran commented on src/components/layout/projects/layout.tsx
> +            beginning to end, or simply looking for advice to get started, get
```suggestion
            start to finish, or looking for advice to get your project off the ground, get
```

2022-10-14 12:40 UTC, Headscracher commented on src/pages/projects/index.tsx
> +        ones, whether they're in-house or in support of other organizations.
Yes same for this one.

2022-10-14 12:50 UTC, merged