Add delay to the redirect if its an error
veganhacktivists/veganhacktivists pull request #194
Opened 2022-12-17 14:42 UTC by prpcodes

Added a delay of 5 seconds to the redirect if getting the request from the backend returns any error.

2022-12-18 11:09 UTC, Headscracher commented
This seems to just work for direct errors thrown by trpc yet. Try calling an invalid or already completed request directly and you'll see in most cases you won't even get redirected yet, or redirected directly.

2022-12-18 12:41 UTC, Headscracher requested changes
This seems to just work for direct errors thrown by trpc yet. Try calling an invalid or already completed request directly and you'll see in most cases you won't even get redirected yet, or redirected directly.

2022-12-27 10:32 UTC, prpcodes commented
> This seems to just work for direct errors thrown by trpc yet. Try calling an invalid or already completed request directly and you'll see in most cases you won't even get redirected yet, or redirected directly.

Thanks for the feedback. I refactored the code to ensure that the redirect only happens if the page is not found and the toast is closed automatically or by the user. It appears that there is a bug in react-toastify, in which the redirect does happen immediately if [_reactStrictMode_ is set to _true_](https://github.com/fkhadra/react-toastify/issues/741#issuecomment-1142595079), but this obviously should not occur in production, so we should be fine.

2023-01-12 19:29 UTC, MatsThieme commented on src/pages/playground/request/[id].tsx
> +        if (e.message === 'NOT_FOUND') {
what about any other error message? should there be an else block?

2023-01-12 19:36 UTC, MatsThieme commented on src/pages/playground/request/[id].tsx
> +        if (e.message === 'NOT_FOUND') {
didnt read the previous conversation.

2023-01-12 19:37 UTC, MatsThieme approved these changes
👍

2023-01-13 20:30 UTC, Headscracher approved these changes

2023-01-13 20:30 UTC, merged