Add blocklist functionality for applicants
veganhacktivists/veganhacktivists pull request #219
Opened 2023-01-29 16:18 UTC by prpcodes

- Add BLockUserButton to Applications.
- Add "Blocked" to the user application status
- Add Blocked to the Status enum
- Upon opening the applyForm, check if the last application was blocked
- Display a toast that prompts the user to contact us
- Send them to the contact form

2023-02-01 22:05 UTC, MatsThieme requested changes

2023-02-01 22:05 UTC, MatsThieme commented on src/components/layout/playground/applyForm.tsx
> +      if (lastApplication?.status === 'Blocked') {
`import { Status } from '@prisma/client';`
Please import the enum and use Status.Blocked

2023-02-01 22:05 UTC, MatsThieme commented on src/pages/playground/admin/applications.tsx
> +                          </DenyButton>
![grafik](https://user-images.githubusercontent.com/45602265/216160842-b1b84c3b-073e-4c5f-80b5-d73dc85cc756.png)
that's a bit cut off, i would use two lines.

2023-02-01 22:05 UTC, MatsThieme commented on src/pages/playground/admin/applications.tsx
> +                                mutate({ id: app.id, status: 'Blocked' });
`import { Status } from '@prisma/client';`
Please import the enum and use Status.Blocked

2023-02-01 22:05 UTC, MatsThieme commented on src/components/layout/playground/applyForm.tsx
> +          }
A toast can easily be missed, to allow the user to navigate on their own, please show this message where the form is currently placed and put a contact button below it. Like this 
![grafik](https://user-images.githubusercontent.com/45602265/216173070-2d8ac404-0cdb-4e09-9fba-89feaa7e23c4.png)

example code
```jsx
  if (isBlocked) {
    return (
      <>
        <h1 className="text-3xl">
          ⚠️ Please contact us before applying for more requests.
        </h1>
        <DarkButton className="w-fit m-auto mt-5" href="/contact">
          Contact
        </DarkButton>
      </>
    );
  }
```

2023-02-04 18:39 UTC, MatsThieme commented on src/components/layout/playground/applyForm.tsx
> -import { DateTime } from 'luxon';
Please fix the line endings in this file

2023-02-10 20:51 UTC, MatsThieme requested changes

2023-02-10 20:51 UTC, MatsThieme commented on src/components/layout/playground/applyForm.tsx
> +const ApplicantBlocked: React.FC = () => {
Please rename to ```RequestApplicationBlocked```

2023-02-10 20:51 UTC, MatsThieme commented on src/components/layout/playground/applyForm.tsx
> +        Please contact us before applying for more requests.
Please change to ```Please contact us before submitting another application.```

2023-02-11 09:09 UTC, MatsThieme approved these changes

2023-02-11 09:11 UTC, MatsThieme commented
Nice work 😃
Please squash your commits when merging to main.

2023-02-11 23:45 UTC, prpcodes commented
> Nice work 😃 Please squash your commits when merging to main.

Thanks, will do 😃

2023-02-12 04:13 UTC, merged