Add translations feature. Invisible for now
veganhacktivists/veganhacktivists pull request #281
Opened 2023-12-04 19:08 UTC by MatsThieme

2023-12-14 12:58 UTC, Headscracher requested changes
![grafik](https://github.com/veganhacktivists/veganhacktivists/assets/16015771/d889a8ed-32f7-4c32-aab4-5d0bb8888615)
In the translated version no-localization is getting displayed

![grafik](https://github.com/veganhacktivists/veganhacktivists/assets/16015771/38e02c39-f7b4-4a1e-bb00-4570eb3e4ce8)
Year in review 2022 is only loading it its translated version

![grafik](https://github.com/veganhacktivists/veganhacktivists/assets/16015771/b597e9ac-8bcb-4d90-b7a1-3aa38a6caee6)
year-in-review-2022 is mostly untranslated ( same as the other one, doesn't need to be done now, but make sure to remember ) and you can see the behavior in the screenshot in multiple sections of the page

2023-12-14 12:58 UTC, Headscracher commented on src/lib/translation/messages.ts
> +import zh from '../../../translation/data/compiled-zh.json';
```suggestion
import en from '../../../translation/data/compiled-en.json';
//import de from '../../../translation/data/compiled-de.json';
//import dev from '../../../translation/data/compiled-dev.json';
//import zh from '../../../translation/data/compiled-zh.json';
```

2023-12-14 12:58 UTC, Headscracher commented on src/components/forms/contactUs.tsx
> +          <Label name="service" label={inputLabels.service} />
```suggestion
          <Label label={inputLabels.service} />
```
I'm not sure tho why this has a label prop in the first place. I would suggest just using the child element

2023-12-14 12:58 UTC, Headscracher commented on src/components/forms/inputs/label.tsx
> +} & ({ label: string } | { children: ReactNode });
I would suggest using React.PropsWithChildren instead of adding children as a prop here to the type. I don't think that the label prop would be needed here

2023-12-14 12:58 UTC, Headscracher commented on src/components/layout/grants/grantsApplication.tsx
Nothing that needs to be changed now, but just be aware that error messages are in some forms now translated and in some not

2023-12-14 12:58 UTC, Headscracher commented on src/components/layout/playground/submitRequestForm.tsx
> +                    <Label name="rate" label="Rate?" showRequiredMark />
```suggestion
                    <Label label="Rate?" showRequiredMark />
```

2023-12-14 12:58 UTC, Headscracher commented on src/components/forms/inputs/label.tsx
>    name: string;
The label shouldn't have a name prop. If we really want a way to add a for attribute to it that should be called for

2023-12-14 12:58 UTC, Headscracher commented on src/components/layout/work/ourWork.tsx
> +            {/* TODO: translate section header */}
Any updates on this?

2023-12-14 12:58 UTC, Headscracher commented on src/components/layout/yearInReview/2021/advisoryService.tsx
The section headers of all of the year in review components aren't translated yet. Doesn't need to happen right now, but I would suggest creating a card for it

2023-12-14 12:58 UTC, Headscracher commented on src/pages/auth/verify-request.tsx
As nextauth is redirecting right now always to /auth/verify-request regardless of the previous lang-setting, this won't be translated right now anyway

2023-12-18 19:54 UTC, MatsThieme commented on src/lib/translation/messages.ts
> +import zh from '../../../translation/data/compiled-zh.json';
I removed the imports for now. Can be added autmatically with an npm script when they are required.

2023-12-18 19:55 UTC, MatsThieme commented on src/components/forms/contactUs.tsx
> +          <Label name="service" label={inputLabels.service} />
using children now

2023-12-18 19:55 UTC, MatsThieme commented on src/components/forms/inputs/label.tsx
> +} & ({ label: string } | { children: ReactNode });
done

2023-12-18 19:56 UTC, MatsThieme commented on src/components/layout/grants/grantsApplication.tsx
Translations are incomplete, I want to get the big changes into main without any visible changes and fix that later.

2023-12-18 19:57 UTC, MatsThieme commented on src/components/layout/playground/submitRequestForm.tsx
> +                    <Label name="rate" label="Rate?" showRequiredMark />
using children now

2023-12-18 19:57 UTC, MatsThieme commented on src/components/forms/inputs/label.tsx
>    name: string;
renamed to htmlFor

2023-12-18 19:57 UTC, MatsThieme commented on src/components/layout/work/ourWork.tsx
> +            {/* TODO: translate section header */}
extended the translation trello card to keep track of this

2023-12-18 19:59 UTC, MatsThieme commented on src/pages/auth/verify-request.tsx
Added to trello card

2024-01-03 12:02 UTC, Headscracher approved these changes, later dismissed
Looks good. Great work :+1:

2024-01-04 18:27 UTC, merged